block1:
  position:
  - 4.5
  - -2.5
  - 0.5
  orientation:
  - 0.0
  - 0.0
  - 0.0
  size:
  - 1.0
  - 1.0
  - 1.0
block2:
  position:
  - -1.5
  - -4.0
  - 0.5
  orientation:
  - 0.0
  - 0.0
  - 0.0
  size:
  - 1.0
  - 1.0
  - 1.0
block3:
  position:
  - -4.5
  - -2.5
  - 0.5
  orientation:
  - 0.0
  - 0.0
  - 0.0
  size:
  - 1.0
  - 1.0
  - 1.0
block4:
  position:
  - -3.5
  - -5.0
  - 0.5
  orientation:
  - 0.0
  - 0.0
  - 0.0
  size:
  - 1.0
  - 1.0
  - 1.0
block5:
  position:
  - -2.5
  - -1.0
  - 0.5
  orientation:
  - 0.0
  - 0.0
  - 0.0
  size:
  - 1.0
  - 1.0
  - 1.0
block6:
  position:
  - 0.0
  - -3.5
  - 0.5
  orientation:
  - 0.0
  - 0.0
  - 0.0
  size:
  - 1.0
  - 1.0
  - 1.0
block7:
  position:
  - -2.5
  - -2.5
  - 0.5
  orientation:
  - 0.0
  - 0.0
  - 0.0
  size:
  - 1.0
  - 1.0
  - 1.0
block8:
  position:
  - 1.5
  - -3.5
  - 0.5
  orientation:
  - 0.0
  - 0.0
  - 0.0
  size:
  - 1.0
  - 1.0
  - 1.0
block9:
  position:
  - 3.5
  - -4.0
  - 0.5
  orientation:
  - 0.0
  - 0.0
  - 0.0
  size:
  - 1.0
  - 1.0
  - 1.0
block10:
  position:
  - -4.0
  - -1.0
  - 0.5
  orientation:
  - 0.0
  - 0.0
  - 0.0
  size:
  - 1.0
  - 1.0
  - 1.0
block11:
  position:
  - 3.0
  - -1.0
  - 0.5
  orientation:
  - 0.0
  - 0.0
  - 0.0
  size:
  - 1.0
  - 1.0
  - 1.0
block12:
  position:
  - -1.0
  - -2.0
  - 0.5
  orientation:
  - 0.0
  - 0.0
  - 0.0
  size:
  - 1.0
  - 1.0
  - 1.0
block13:
  position:
  - 0.5
  - -2.0
  - 0.5
  orientation:
  - 0.0
  - 0.0
  - 0.0
  size:
  - 1.0
  - 1.0
  - 1.0
block14:
  position:
  - 0.5
  - -5.0
  - 0.5
  orientation:
  - 0.0
  - 0.0
  - 0.0
  size:
  - 1.0
  - 1.0
  - 1.0
block15:
  position:
  - 5.0
  - -4.5
  - 0.5
  orientation:
  - 0.0
  - 0.0
  - 0.0
  size:
  - 1.0
  - 1.0
  - 1.0
block16:
  position:
  - -5.0
  - -4.5
  - 0.5
  orientation:
  - 0.0
  - 0.0
  - 0.0
  size:
  - 1.0
  - 1.0
  - 1.0
block17:
  position:
  - 3.0
  - -2.5
  - 0.5
  orientation:
  - 0.0
  - 0.0
  - 0.0
  size:
  - 1.0
  - 1.0
  - 1.0
block18:
  position:
  - 2.0
  - -5.0
  - 0.5
  orientation:
  - 0.0
  - 0.0
  - 0.0
  size:
  - 1.0
  - 1.0
  - 1.0
robot:
  position:
  - -6.0
  - -6.0
  - 0.0
  orientation:
  - 0.0
  - 0.0
  - 0.0