# Place object service
# Request
string target_name
string frame_id

---
# Response
bool success
int32 result
string message

int32 SUCCESS = 0
int32 IK_FAILED = 1
int32 TF_FAILED = 2
int32 GRIPPER_EMPTY = 3
int32 TARGET_OCCUPIED = 4
int32 RELEASE_FAILED = 5
int32 RETURN_HOME_FAILED = 6